---
deployment:
  tasks:
    - export DEPLOY_ENV=production
    - /usr/local/bin/npm install
    - /usr/local/bin/npm run build
    - export DEPLOY_PATH=/home/rgjg6580/laurent.c2sportsprod.com/admin
    - rsync -avz out/ /home/rgjg6580/laurent.c2sportsprod.com/admin/
    - rsync -avz out/ $DEPLOY_PATH/
